### ISSUE TITLE
Error in runBispectrumExtractor.py when printing all configurations

### ISSUE THREAD

**Issue by anikhalder** [llinke1/BiG#1]
When I run the runBispectrumExtractor.py for computing 'all' configurations, the code gives an error in the output section in line:

`print(kbins_mid[i], kbins_mid[j], kbins_mid[k], bispec[ix], norm[ix], bispec[ix]/norm[ix]*Xtract.prefactor, file=o)`

--> IndexError: list index out of range

I believe this is because the triangle inequality condition is not checked before printing out the bispectrum values inside the nested loop. This can be solved for example by adding something along the lines of:

`k_arr = np.sort(np.array([kbins_mid[i], kbins_mid[j], kbins_mid[k]]))`
`if(k_arr[0] + k_arr[1] < k_arr[2]):`
`       continue`
`print(kbins_mid[i], kbins_mid[j], kbins_mid[k], bispec[ix], norm[ix], bispec[ix]/norm[ix]*Xtract.prefactor, file=o)`

**Comment by llinke1** [comment]
Hi Anik,
This issue should be fixed now! There was a bug in bispectrumExtractor.py, where the code would not calculate the bispectrum for all possible k-value combinations but left out some. 
Let me know, if the error persists!
